name: Update

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: github-pages
      - name: Clean repo
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: |
          pip install --user git-filter-repo &&
          git filter-repo --path-glob '*.jpg' --invert-paths --refs github-pages
      - name: Setup CLI
        run: |
          curl -LO https://github.com/pcolusso/himawari-render/releases/download/tip/himawari_cli &&
          chmod +x himawari_cli
      - name: Run CLI
        run: ./himawari_cli image --location docs/image.jpg
      - name: Generate iPhone wallpaper
        run: ./himawari_cli wallpaper -q 2 1170 2532 --output docs/iPhoneX.jpg
      - name: Publish update
        uses: EndBug/add-and-commit@v8
        with:
          add: docs/*
          author_name: GitHub Actions
          author_email: noone@example.com
          message: 'The world keeps turning'
          push: origin github-pages --force